declare function stripObject({ object }: {
    object: any;
}): any;
declare function getObjectById({ token, objectId, objectType, objectIdType, callback, dbCallFunc, commandName, needsAccess, internalCallUser, searchParams, }: {
    token: any;
    objectId: any;
    objectType: any;
    objectIdType: any;
    callback: any;
    dbCallFunc: any;
    commandName: any;
    needsAccess: any;
    internalCallUser: any;
    searchParams?: never[] | undefined;
}): void;
declare function getObjects({ token, objectsType, callback, dbCallFunc, commandName, internalCallUser, shouldSort, sortName, fallbackSortName, ignoreAuth, getParams, }: {
    token: any;
    objectsType: any;
    callback: any;
    dbCallFunc: any;
    commandName: any;
    internalCallUser: any;
    shouldSort: any;
    sortName: any;
    fallbackSortName: any;
    ignoreAuth?: boolean | undefined;
    getParams?: never[] | undefined;
}): void;
declare function updateObject({ objectId, token, object, commandName, objectType, dbCallFunc, emitType, io, socket, objectIdType, getDbCallFunc, getCommandName, callback, internalCallUser, options, limitAccessLevel, toStrip, }: {
    objectId: any;
    token: any;
    object: any;
    commandName: any;
    objectType: any;
    dbCallFunc: any;
    emitType: any;
    io: any;
    socket: any;
    objectIdType: any;
    getDbCallFunc: any;
    getCommandName: any;
    callback: any;
    internalCallUser: any;
    options: any;
    limitAccessLevel?: boolean | undefined;
    toStrip?: never[] | undefined;
}): void;
declare function removeObject({ objectId, token, commandName, objectType, dbCallFunc, emitType, io, objectIdType, getDbCallFunc, getCommandName, emitTypeGenerator, callback, socket, internalCallUser, }: {
    objectId: any;
    token: any;
    commandName: any;
    objectType: any;
    dbCallFunc: any;
    emitType: any;
    io: any;
    objectIdType: any;
    getDbCallFunc: any;
    getCommandName: any;
    emitTypeGenerator: any;
    callback: any;
    socket: any;
    internalCallUser: any;
}): void;
declare function updateAccess({ objectId, token, teamAdminIds, userAdminIds, userIds, teamIds, bannedIds, shouldRemove, commandName, objectType, dbCallFunc, emitType, io, objectIdType, getDbCallFunc, getCommandName, callback, internalCallUser, options, socket, toStrip, }: {
    objectId: any;
    token: any;
    teamAdminIds: any;
    userAdminIds: any;
    userIds: any;
    teamIds: any;
    bannedIds: any;
    shouldRemove: any;
    commandName: any;
    objectType: any;
    dbCallFunc: any;
    emitType: any;
    io: any;
    objectIdType: any;
    getDbCallFunc: any;
    getCommandName: any;
    callback: any;
    internalCallUser: any;
    options: any;
    socket: any;
    toStrip?: never[] | undefined;
}): void;
export { stripObject };
export { removeObject };
export { getObjectById };
export { updateObject };
export { getObjects };
export { updateAccess };
