import AlreadyExists from './AlreadyExists.js';
import Banned from './Banned.js';
import Database from './Database.js';
import DoesNotExist from './DoesNotExist.js';
import Expired from './Expired.js';
import External from './External.js';
import GeneralError, { ErrorTypes } from './GeneralError.js';
import Incorrect from './Incorrect.js';
import Insufficient from './Insufficient.js';
import Internal from './Internal.js';
import InvalidCharacters from './InvalidCharacters.js';
import InvalidData from './InvalidData.js';
import InvalidLength from './InvalidLength.js';
import InvalidMail from './InvalidMail.js';
import NeedsVerification from './NeedsVerification.js';
import NotAllowed from './NotAllowed.js';
import TooFrequent from './TooFrequent.js';
declare const _default: {
    InvalidData: typeof InvalidData;
    TooFrequent: typeof TooFrequent;
    InvalidMail: typeof InvalidMail;
    Expired: typeof Expired;
    Internal: typeof Internal;
    Insufficient: typeof Insufficient;
    Banned: typeof Banned;
    NeedsVerification: typeof NeedsVerification;
    Incorrect: typeof Incorrect;
    DoesNotExist: typeof DoesNotExist;
    External: typeof External;
    AlreadyExists: typeof AlreadyExists;
    Database: typeof Database;
    InvalidLength: typeof InvalidLength;
    InvalidCharacters: typeof InvalidCharacters;
    NotAllowed: typeof NotAllowed;
    ErrorTypes: typeof ErrorTypes;
    General: typeof GeneralError;
};
export default _default;
